CREATE TABLE Addresses (
    AddressID NUMBER(5) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Street VARCHAR2(100) NOT NULL,
    City VARCHAR2(50) NOT NULL,
    State CHAR(2) NOT NULL,
    Zip VARCHAR2(10) NOT NULL,
        CONSTRAINT addresses_addressid_pk PRIMARY KEY(AddressID)
);

INSERT INTO Addresses (
    Street,
    City,
    State,
    Zip)
    VALUES ('2021 Memory Lane', 'Paradise', 'FL', 12345);

INSERT INTO Addresses (
    Street,
    City,
    State,
    Zip)
    VALUES ('2000 Haskins Drive', 'Somewhere', 'NM', 34556);

INSERT INTO Addresses (
    Street,
    City,
    State,
    Zip)
    VALUES ('123 Aye Bee Cee Way', 'Hollywood', 'CA', 99932);

INSERT INTO Addresses (
    Street,
    City,
    State,
    Zip)
    VALUES ('1234 Lost Ave.',  'Billings', 'MN', 29842); 

INSERT INTO Addresses (
    Street,
    City,
    State,
    Zip)
    VALUES ('4500 Montana Way', 'Post', 'ID', 83921);

INSERT INTO Addresses (
    Street,
    City,
    State,
    Zip)
    VALUES ('990 Never Drive', 'Please', 'NY', 12349);


CREATE TABLE Customers (
    CustomerID NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    LastName VARCHAR2(50) NOT NULL,
    FirstName VARCHAR2(50) NOT NULL,
    AddressID NUMBER(5),
    Phone  VARCHAR2(12),
    Email VARCHAR2(100),
        CONSTRAINT customers_customerid_pk
        PRIMARY KEY(CustomerID),
        CONSTRAINT customers_addressid_fk
        FOREIGN KEY (AddressID)
            REFERENCES Addresses(AddressID)
);

INSERT INTO Customers (
    LastName,
    FirstName,
    AddressID,
    Phone,
    Email)
    VALUES ('Doe', 'John', 1, '555-867-5309', 'jdoe@email.com');

INSERT INTO Customers (
    LastName,
    FirstName,
    AddressID,
    Phone,
    Email)
    VALUES ('Dem', 'Demo', 2, '555-555-5555', 'ddemo@email.com');

INSERT INTO Customers (
    LastName,
    FirstName,
    AddressID,
    Phone,
    Email)
    VALUES ('Smith', 'Tess', 3, '827-323-9852', 'tsmith@email.com');

INSERT INTO Customers (
    LastName,
    FirstName,
    AddressID,
    Phone,
    Email)
    VALUES ('Sims', 'Ioto', 4, '555-923-0298', 'isims@email.com');

INSERT INTO Customers (
    LastName,
    FirstName,
    AddressID,
    Phone,
    Email)
    VALUES ('Jonhs', 'Hoppin', 5, '555-392-4853', 'jhop@email.com');

CREATE TABLE Products (
    ProductID NUMBER(2) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Origin VARCHAR2(22),
    Softness NUMBER(1),
    Price DECIMAL(4,2),
    CONSTRAINT products_pk PRIMARY KEY(ProductID)
);

INSERT INTO Products (Origin, Softness, Price)  
	VALUES ('Military Press Pillows', 1, 19.99);

INSERT INTO Products (Origin, Softness, Price)  
	VALUES ('Military Press Pillows', 3, 29.99);

INSERT INTO Products (Origin, Softness, Price)  
	VALUES ('Felon Feathers', 5, 13.99);

INSERT INTO Products (Origin, Softness, Price)  
    VALUES ('Military Press Pillows', 2, 29.99);

INSERT INTO Products (Origin, Softness, Price)  
    VALUES ('Military Press Pillows', 4, 19.99);

INSERT INTO Products (Origin, Softness, Price)  
    VALUES ('Felon Feathers', 3, 19.99);

INSERT INTO Products (Origin, Softness, Price)  
    VALUES ('Felon Feathers', 2, 25.99);

CREATE TABLE Transactions ( 
	TransactionID NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY, 
	PaymentType VARCHAR(50), 
	PaymentInfo VARCHAR(50), 
	BillingAddress NUMBER(5),
    CONSTRAINT transactions_pk PRIMARY KEY (TransactionID),
    CONSTRAINT transactions_billingaddress_fk
        FOREIGN KEY (BillingAddress)
            REFERENCES Addresses(AddressID)
);

INSERT INTO Transactions (PaymentType, PaymentInfo, BillingAddress) 
	VALUES ('Credit', '2345-3928-1938-1293', 1 
);

INSERT INTO Transactions (PaymentType, PaymentInfo, BillingAddress) 
	VALUES ('Credit', '8403-2048-0958-2049', 2
);

INSERT INTO Transactions (PaymentType, PaymentInfo, BillingAddress) 
	VALUES ('Check', 'Citi Bank', 4 
);

INSERT INTO Transactions (PaymentType, PaymentInfo, BillingAddress) 
	VALUES ('Check', 'Chase Bank', 5
);

INSERT INTO Transactions (PaymentType, PaymentInfo, BillingAddress) 
	VALUES ('Credit', '2910-3492-9482-9382', 6
);

CREATE TABLE Orders (
    OrderID NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ShippingAddress NUMBER(5),
    TransactionID NUMBER(6),
    CustomerID NUMBER(4),
        CONSTRAINT orders_pk PRIMARY KEY(OrderID),
        CONSTRAINT transaction_fk FOREIGN KEY (TransactionID) REFERENCES Transactions(TransactionID) ON DELETE CASCADE,
        CONSTRAINT customer_fk FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID) ON DELETE CASCADE 
);

CREATE TABLE Order_Product ( 
	ProductID NUMBER(2), 
	OrderID NUMBER(6), 
        CONSTRAINT order_product_pk PRIMARY KEY(ProductID, OrderID),
	    CONSTRAINT product_fk FOREIGN KEY (ProductID) REFERENCES Products(ProductID) ON DELETE CASCADE, 
	    CONSTRAINT order_fk FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE 
);

INSERT INTO Orders (ShippingAddress, TransactionID, CustomerID)
    VALUES (1, 1, 1);

INSERT INTO Orders (ShippingAddress, TransactionID, CustomerID)
    VALUES (5, 4, 5);

INSERT INTO Orders (ShippingAddress, TransactionID, CustomerID)
    VALUES (6, 5, 5);

INSERT INTO Orders (ShippingAddress, TransactionID, CustomerID)
    VALUES (1, 1, 1);

INSERT INTO Orders (ShippingAddress, TransactionID, CustomerID)
    VALUES (2, 2, 2);

INSERT INTO Orders (ShippingAddress, TransactionID, CustomerID)
    VALUES (4, 3, 4);

INSERT INTO ORDER_PRODUCT VALUES (1, 1);

INSERT INTO ORDER_PRODUCT VALUES (1, 4);

INSERT INTO ORDER_PRODUCT VALUES (2, 1);

INSERT INTO ORDER_PRODUCT VALUES (2, 2);

INSERT INTO ORDER_PRODUCT VALUES (3, 4);

INSERT INTO ORDER_PRODUCT VALUES (3, 5);

INSERT INTO ORDER_PRODUCT VALUES (4, 1);

INSERT INTO ORDER_PRODUCT VALUES (5, 3);

INSERT INTO ORDER_PRODUCT VALUES (5, 4);

INSERT INTO ORDER_PRODUCT VALUES (6, 1);

INSERT INTO ORDER_PRODUCT VALUES (6, 6);